### Configurações Globais
@baseUrl = http://localhost:3000
@contentType = application/json

### ----------------------------------------------------
### AUTENTICAÇÃO
### ----------------------------------------------------

# @name loginAdmin
# Realizar login para obter o token do administrador
POST {{baseUrl}}/login
Content-Type: {{contentType}}

{
  "email": "admin@exemplo.com",
  "password": "senhaAdmin123"
}

###

# @name loginAdopter
# Realizar login para obter o token do adotante
POST {{baseUrl}}/login
Content-Type: {{contentType}}

{
  "email": "adopter@exemplo.com",
  "password": "senhaAdopter123"
}

### ----------------------------------------------------
### CONFIGURAÇÃO DOS TOKENS AUTOMÁTICOS
### ----------------------------------------------------
@tokenAdmin = {{loginAdmin.response.body.token}}
@tokenAdopter = {{loginAdopter.response.body.token}}

### ----------------------------------------------------
### ROTAS DE SUCESSO
### ----------------------------------------------------

# Realizar adoção de um pet já cadastrado e disponível (Apenas Adopter)
# @name criarAdocao
POST {{baseUrl}}/adoptions
Authorization: Bearer {{tokenAdopter}}
Content-Type: {{contentType}}

{
  "pet_id": 8
}

###

# Listar todas as adoções (Apenas Admin)
GET {{baseUrl}}/adoptions
Authorization: Bearer {{tokenAdmin}}

### ----------------------------------------------------
### CENÁRIOS DE ERRO - ADOÇÕES
### ----------------------------------------------------

# 1. Erro de Autorização: Admin tentando adotar um pet
POST {{baseUrl}}/adoptions
Authorization: Bearer {{tokenAdmin}}
Content-Type: {{contentType}}

{
  "pet_id": 3
}

###

# 2. Erro de Autorização: Adopter tentando listar adoções
GET {{baseUrl}}/adoptions
Authorization: Bearer {{tokenAdopter}}

###

# 3. Erro de Autenticação: Acesso sem token nas rotas protegidas
GET {{baseUrl}}/adoptions

###

# 4. Erro na Criação: Campo obrigatório ausente
POST {{baseUrl}}/adoptions
Authorization: Bearer {{tokenAdopter}}
Content-Type: {{contentType}}

{}

###

# 5. Erro na Criação: Pet inexistente
POST {{baseUrl}}/adoptions
Authorization: Bearer {{tokenAdopter}}
Content-Type: {{contentType}}

{
  "pet_id": 999999
}

###

# 6. Erro na Criação: Mesmo usuário tentando adotar o mesmo pet novamente
POST {{baseUrl}}/adoptions
Authorization: Bearer {{tokenAdopter}}
Content-Type: {{contentType}}

{
  "pet_id": 3
}

### ----------------------------------------------------
### DELEÇÃO
### ----------------------------------------------------

# Deletar registro de adoção criado neste arquivo (Apenas Admin)
DELETE {{baseUrl}}/adoptions/4
Authorization: Bearer {{tokenAdmin}}

###

# Erro de Deleção: Adoção inexistente
DELETE {{baseUrl}}/adoptions/999999
Authorization: Bearer {{tokenAdmin}}
